namespace ScintillaNet.Lexers
{
    public enum PYTHON
    {    
        DEFAULT = 0,
        COMMENTLINE = 1,
        NUMBER = 2,
        STRING = 3,
        CHARACTER = 4,
        WORD = 5,
        TRIPLE = 6,
        TRIPLEDOUBLE = 7,
        CLASSNAME = 8,
        DEFNAME = 9,
        OPERATOR = 10,
        IDENTIFIER = 11,
        COMMENTBLOCK = 12,
        STRINGEOL = 13,
        WORD2 = 14,
        DECORATOR = 15,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum NIMROD
    {
        DEFAULT = 0,
        COMMENTLINE = 1,
        NUMBER = 2,
        STRING = 3,
        CHARACTER = 4,
        WORD = 5,
        TRIPLE = 6,
        TRIPLEDOUBLE = 7,
        CLASSNAME = 8,
        DEFNAME = 9,
        OPERATOR = 10,
        IDENTIFIER = 11,
        COMMENTBLOCK = 12,
        STRINGEOL = 13,
        WORD2 = 14,
        DECORATOR = 15,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum CPP
    {    
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTLINE = 2,
        COMMENTDOC = 3,
        NUMBER = 4,
        WORD = 5,
        STRING = 6,
        CHARACTER = 7,
        UUID = 8,
        PREPROCESSOR = 9,
        OPERATOR = 10,
        IDENTIFIER = 11,
        STRINGEOL = 12,
        VERBATIM = 13,
        REGEX = 14,
        COMMENTLINEDOC = 15,
        WORD2 = 16,
        COMMENTDOCKEYWORD = 17,
        COMMENTDOCKEYWORDERROR = 18,
        GLOBALCLASS = 19,
        STRINGRAW = 20,
        TRIPLEVERBATIM = 21,
        HASHQUOTEDSTRING = 22,
        PREPROCESSORCOMMENT = 23,
        WORD3 = 24,
        WORD4 = 25,
        WORD5 = 26,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum BULLANT
    {
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTLINE = 2,
        COMMENTDOC = 3,
        NUMBER = 4,
        WORD = 5,
        STRING = 6,
        CHARACTER = 7,
        UUID = 8,
        PREPROCESSOR = 9,
        OPERATOR = 10,
        IDENTIFIER = 11,
        STRINGEOL = 12,
        VERBATIM = 13,
        REGEX = 14,
        COMMENTLINEDOC = 15,
        WORD2 = 16,
        COMMENTDOCKEYWORD = 17,
        COMMENTDOCKEYWORDERROR = 18,
        GLOBALCLASS = 19,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum D
    {
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTLINE = 2,
        COMMENTDOC = 3,
        COMMENTNESTED = 4,
        NUMBER = 5,
        WORD = 6,
        WORD2 = 7,
        WORD3 = 8,
        TYPEDEF = 9,
        STRING = 10,
        STRINGEOL = 11,
        CHARACTER = 12,
        OPERATOR = 13,
        IDENTIFIER = 14,
        COMMENTLINEDOC = 15,
        COMMENTDOCKEYWORD = 16,
        COMMENTDOCKEYWORDERROR = 17,
        STRINGB = 18,
        STRINGR = 19,
        WORD5 = 20,
        WORD6 = 21,
        WORD7 = 22,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum TCL
    {
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTLINE = 2,
        NUMBER = 3,
        WORD_IN_QUOTE = 4,
        IN_QUOTE = 5,
        OPERATOR = 6,
        IDENTIFIER = 7,
        SUBSTITUTION = 8,
        SUB_BRACE = 9,
        MODIFIER = 10,
        EXPAND = 11,
        WORD = 12,
        WORD2 = 13,
        WORD3 = 14,
        WORD4 = 15,
        WORD5 = 16,
        WORD6 = 17,
        WORD7 = 18,
        WORD8 = 19,
        COMMENT_BOX = 20,
        BLOCK_COMMENT = 21,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum HTML
    {
        DEFAULT = 0,
        TAG = 1,
        TAGUNKNOWN = 2,
        ATTRIBUTE = 3,
        ATTRIBUTEUNKNOWN = 4,
        NUMBER = 5,
        DOUBLESTRING = 6,
        SINGLESTRING = 7,
        OTHER = 8,
        COMMENT = 9,
        ENTITY = 10,
        TAGEND = 11,
        XMLSTART = 12,
        XMLEND = 13,
        SCRIPT = 14,
        ASP = 15,
        ASPAT = 16,
        CDATA = 17,
        QUESTION = 18,
        VALUE = 19,
        XCCOMMENT = 20,
        SGML_DEFAULT = 21,
        SGML_COMMAND = 22,
        SGML_1ST_PARAM = 23,
        SGML_DOUBLESTRING = 24,
        SGML_SIMPLESTRING = 25,
        SGML_ERROR = 26,
        SGML_SPECIAL = 27,
        SGML_ENTITY = 28,
        SGML_COMMENT = 29,
        SGML_1ST_PARAM_COMMENT = 30,
        SGML_BLOCK_DEFAULT = 31,
        J_START = 40,
        J_DEFAULT = 41,
        J_COMMENT = 42,
        J_COMMENTLINE = 43,
        J_COMMENTDOC = 44,
        J_NUMBER = 45,
        J_WORD = 46,
        J_KEYWORD = 47,
        J_DOUBLESTRING = 48,
        J_SINGLESTRING = 49,
        J_SYMBOLS = 50,
        J_STRINGEOL = 51,
        J_REGEX = 52,
        JA_START = 55,
        JA_DEFAULT = 56,
        JA_COMMENT = 57,
        JA_COMMENTLINE = 58,
        JA_COMMENTDOC = 59,
        JA_NUMBER = 60,
        JA_WORD = 61,
        JA_KEYWORD = 62,
        JA_DOUBLESTRING = 63,
        JA_SINGLESTRING = 64,
        JA_SYMBOLS = 65,
        JA_STRINGEOL = 66,
        JA_REGEX = 67,
        B_START = 70,
        B_DEFAULT = 71,
        B_COMMENTLINE = 72,
        B_NUMBER = 73,
        B_WORD = 74,
        B_STRING = 75,
        B_IDENTIFIER = 76,
        B_STRINGEOL = 77,
        BA_START = 80,
        BA_DEFAULT = 81,
        BA_COMMENTLINE = 82,
        BA_NUMBER = 83,
        BA_WORD = 84,
        BA_STRING = 85,
        BA_IDENTIFIER = 86,
        BA_STRINGEOL = 87,
        P_START = 90,
        P_DEFAULT = 91,
        P_COMMENTLINE = 92,
        P_NUMBER = 93,
        P_STRING = 94,
        P_CHARACTER = 95,
        P_WORD = 96,
        P_TRIPLE = 97,
        P_TRIPLEDOUBLE = 98,
        P_CLASSNAME = 99,
        P_DEFNAME = 100,
        P_OPERATOR = 101,
        P_IDENTIFIER = 102,
        PHP_COMPLEX_VARIABLE = 104,
        PA_START = 105,
        PA_DEFAULT = 106,
        PA_COMMENTLINE = 107,
        PA_NUMBER = 108,
        PA_STRING = 109,
        PA_CHARACTER = 110,
        PA_WORD = 111,
        PA_TRIPLE = 112,
        PA_TRIPLEDOUBLE = 113,
        PA_CLASSNAME = 114,
        PA_DEFNAME = 115,
        PA_OPERATOR = 116,
        PA_IDENTIFIER = 117,
        PHP_DEFAULT = 118,
        PHP_HSTRING = 119,
        PHP_SIMPLESTRING = 120,
        PHP_WORD = 121,
        PHP_NUMBER = 122,
        PHP_VARIABLE = 123,
        PHP_COMMENT = 124,
        PHP_COMMENTLINE = 125,
        PHP_HSTRING_VARIABLE = 126,
        PHP_OPERATOR = 127,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum XML
    {
        DEFAULT = 0,
        TAG = 1,
        TAGUNKNOWN = 2,
        ATTRIBUTE = 3,
        ATTRIBUTEUNKNOWN = 4,
        NUMBER = 5,
        DOUBLESTRING = 6,
        SINGLESTRING = 7,
        OTHER = 8,
        COMMENT = 9,
        ENTITY = 10,
        TAGEND = 11,
        XMLSTART = 12,
        XMLEND = 13,
        SCRIPT = 14,
        ASP = 15,
        ASPAT = 16,
        CDATA = 17,
        QUESTION = 18,
        VALUE = 19,
        XCCOMMENT = 20,
        SGML_DEFAULT = 21,
        SGML_COMMAND = 22,
        SGML_1ST_PARAM = 23,
        SGML_DOUBLESTRING = 24,
        SGML_SIMPLESTRING = 25,
        SGML_ERROR = 26,
        SGML_SPECIAL = 27,
        SGML_ENTITY = 28,
        SGML_COMMENT = 29,
        SGML_1ST_PARAM_COMMENT = 30,
        SGML_BLOCK_DEFAULT = 31,
        J_START = 40,
        J_DEFAULT = 41,
        J_COMMENT = 42,
        J_COMMENTLINE = 43,
        J_COMMENTDOC = 44,
        J_NUMBER = 45,
        J_WORD = 46,
        J_KEYWORD = 47,
        J_DOUBLESTRING = 48,
        J_SINGLESTRING = 49,
        J_SYMBOLS = 50,
        J_STRINGEOL = 51,
        J_REGEX = 52,
        JA_START = 55,
        JA_DEFAULT = 56,
        JA_COMMENT = 57,
        JA_COMMENTLINE = 58,
        JA_COMMENTDOC = 59,
        JA_NUMBER = 60,
        JA_WORD = 61,
        JA_KEYWORD = 62,
        JA_DOUBLESTRING = 63,
        JA_SINGLESTRING = 64,
        JA_SYMBOLS = 65,
        JA_STRINGEOL = 66,
        JA_REGEX = 67,
        B_START = 70,
        B_DEFAULT = 71,
        B_COMMENTLINE = 72,
        B_NUMBER = 73,
        B_WORD = 74,
        B_STRING = 75,
        B_IDENTIFIER = 76,
        B_STRINGEOL = 77,
        BA_START = 80,
        BA_DEFAULT = 81,
        BA_COMMENTLINE = 82,
        BA_NUMBER = 83,
        BA_WORD = 84,
        BA_STRING = 85,
        BA_IDENTIFIER = 86,
        BA_STRINGEOL = 87,
        P_START = 90,
        P_DEFAULT = 91,
        P_COMMENTLINE = 92,
        P_NUMBER = 93,
        P_STRING = 94,
        P_CHARACTER = 95,
        P_WORD = 96,
        P_TRIPLE = 97,
        P_TRIPLEDOUBLE = 98,
        P_CLASSNAME = 99,
        P_DEFNAME = 100,
        P_OPERATOR = 101,
        P_IDENTIFIER = 102,
        PHP_COMPLEX_VARIABLE = 104,
        PA_START = 105,
        PA_DEFAULT = 106,
        PA_COMMENTLINE = 107,
        PA_NUMBER = 108,
        PA_STRING = 109,
        PA_CHARACTER = 110,
        PA_WORD = 111,
        PA_TRIPLE = 112,
        PA_TRIPLEDOUBLE = 113,
        PA_CLASSNAME = 114,
        PA_DEFNAME = 115,
        PA_OPERATOR = 116,
        PA_IDENTIFIER = 117,
        PHP_DEFAULT = 118,
        PHP_HSTRING = 119,
        PHP_SIMPLESTRING = 120,
        PHP_WORD = 121,
        PHP_NUMBER = 122,
        PHP_VARIABLE = 123,
        PHP_COMMENT = 124,
        PHP_COMMENTLINE = 125,
        PHP_HSTRING_VARIABLE = 126,
        PHP_OPERATOR = 127,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum PERL
    {    
        DEFAULT = 0,
        ERROR = 1,
        COMMENTLINE = 2,
        POD = 3,
        NUMBER = 4,
        WORD = 5,
        STRING = 6,
        CHARACTER = 7,
        PUNCTUATION = 8,
        PREPROCESSOR = 9,
        OPERATOR = 10,
        IDENTIFIER = 11,
        SCALAR = 12,
        ARRAY = 13,
        HASH = 14,
        SYMBOLTABLE = 15,
        VARIABLE_INDEXER = 16,
        REGEX = 17,
        REGSUBST = 18,
        LONGQUOTE = 19,
        BACKTICKS = 20,
        DATASECTION = 21,
        HERE_DELIM = 22,
        HERE_Q = 23,
        HERE_QQ = 24,
        HERE_QX = 25,
        STRING_Q = 26,
        STRING_QQ = 27,
        STRING_QX = 28,
        STRING_QR = 29,
        STRING_QW = 30,
        POD_VERB = 31,
        SUB_PROTOTYPE = 40,
        FORMAT_IDENT = 41,
        FORMAT = 42,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum RUBY
    {    
        DEFAULT = 0,
        ERROR = 1,
        COMMENTLINE = 2,
        POD = 3,
        NUMBER = 4,
        WORD = 5,
        STRING = 6,
        CHARACTER = 7,
        CLASSNAME = 8,
        DEFNAME = 9,
        OPERATOR = 10,
        IDENTIFIER = 11,
        REGEX = 12,
        GLOBAL = 13,
        SYMBOL = 14,
        MODULE_NAME = 15,
        INSTANCE_VAR = 16,
        CLASS_VAR = 17,
        BACKTICKS = 18,
        DATASECTION = 19,
        HERE_DELIM = 20,
        HERE_Q = 21,
        HERE_QQ = 22,
        HERE_QX = 23,
        STRING_Q = 24,
        STRING_QQ = 25,
        STRING_QX = 26,
        STRING_QR = 27,
        STRING_QW = 28,
        WORD_DEMOTED = 29,
        STDIN = 30,
        STDOUT = 31,
        STDERR = 40,
        UPPER_BOUND = 41,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum VB
    {    
        DEFAULT = 0,
        COMMENT = 1,
        NUMBER = 2,
        KEYWORD = 3,
        STRING = 4,
        PREPROCESSOR = 5,
        OPERATOR = 6,
        IDENTIFIER = 7,
        DATE = 8,
        STRINGEOL = 9,
        KEYWORD2 = 10,
        KEYWORD3 = 11,
        KEYWORD4 = 12,
        CONSTANT = 13,
        ASM = 14,
        LABEL = 15,
        ERROR = 16,
        HEXNUMBER = 17,
        BINNUMBER = 18,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum VBSCRIPT
    {
        DEFAULT = 0,
        COMMENT = 1,
        NUMBER = 2,
        KEYWORD = 3,
        STRING = 4,
        PREPROCESSOR = 5,
        OPERATOR = 6,
        IDENTIFIER = 7,
        DATE = 8,
        STRINGEOL = 9,
        KEYWORD2 = 10,
        KEYWORD3 = 11,
        KEYWORD4 = 12,
        CONSTANT = 13,
        ASM = 14,
        LABEL = 15,
        ERROR = 16,
        HEXNUMBER = 17,
        BINNUMBER = 18,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum POWERBASIC
    {
        DEFAULT = 0,
        COMMENT = 1,
        NUMBER = 2,
        KEYWORD = 3,
        STRING = 4,
        PREPROCESSOR = 5,
        OPERATOR = 6,
        IDENTIFIER = 7,
        DATE = 8,
        STRINGEOL = 9,
        KEYWORD2 = 10,
        KEYWORD3 = 11,
        KEYWORD4 = 12,
        CONSTANT = 13,
        ASM = 14,
        LABEL = 15,
        ERROR = 16,
        HEXNUMBER = 17,
        BINNUMBER = 18,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum PROPERTIES
    {    
        DEFAULT = 0,
        COMMENT = 1,
        SECTION = 2,
        ASSIGNMENT = 3,
        DEFVAL = 4,
        KEY = 5,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum LATEX
    {
        DEFAULT = 0,
        COMMAND = 1,
        TAG = 2,
        MATH = 3,
        COMMENT = 4,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum LUA
    {
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTLINE = 2,
        COMMENTDOC = 3,
        NUMBER = 4,
        WORD = 5,
        STRING = 6,
        CHARACTER = 7,
        LITERALSTRING = 8,
        PREPROCESSOR = 9,
        OPERATOR = 10,
        IDENTIFIER = 11,
        STRINGEOL = 12,
        WORD2 = 13,
        WORD3 = 14,
        WORD4 = 15,
        WORD5 = 16,
        WORD6 = 17,
        WORD7 = 18,
        WORD8 = 19,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum ERRORLIST
    {    
        DEFAULT = 0,
        PYTHON = 1,
        GCC = 2,
        MS = 3,
        CMD = 4,
        BORLAND = 5,
        PERL = 6,
        NET = 7,
        LUA = 8,
        CTAG = 9,
        DIFF_CHANGED = 10,
        DIFF_ADDITION = 11,
        DIFF_DELETION = 12,
        DIFF_MESSAGE = 13,
        PHP = 14,
        ELF = 15,
        IFC = 16,
        IFORT = 17,
        ABSF = 18,
        TIDY = 19,
        JAVA_STACK = 20,
        VALUE = 21,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum BATCH
    {    
        DEFAULT = 0,
        COMMENT = 1,
        WORD = 2,
        LABEL = 3, // line starting with ':'
        HIDE = 4, // '@'
        COMMAND = 5,
        IDENTIFIER = 6, // %%x, %EnvironmentVar%, !EnvironmentVar!
        OPERATOR = 7,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum MAKEFILE
    {    
        DEFAULT = 0,
        COMMENT = 1,
        PREPROCESSOR = 2,
        IDENTIFIER = 3,
        OPERATOR = 4,
        TARGET = 5,
        IDEOL = 9,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum DIFF
    {    
        DEFAULT = 0,
        COMMENT = 1,
        COMMAND = 2,
        HEADER = 3,
        POSITION = 4,
        DELETED = 5,
        ADDED = 6,
        CHANGED = 7,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39,
        MAX = 127
    }
    
    public enum CONF
    {    
        DEFAULT = 0,
        COMMENT = 1,
        NUMBER = 2,
        IDENTIFIER = 3,
        EXTENSION = 4,
        PARAMETER = 5,
        STRING = 6,
        OPERATOR = 7,
        IP = 8,
        DIRECTIVE = 9,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum AVE
    {    
        DEFAULT = 0,
        COMMENT = 1,
        NUMBER = 2,
        WORD = 3,
        STRING = 6,
        ENUM = 7,
        STRINGEOL = 8,
        IDENTIFIER = 9,
        OPERATOR = 10,
        WORD1 = 11,
        WORD2 = 12,
        WORD3 = 13,
        WORD4 = 14,
        WORD5 = 15,
        WORD6 = 16,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum ADA
    {    
        DEFAULT = 0,
        WORD = 1,
        IDENTIFIER = 2,
        NUMBER = 3,
        DELIMITER = 4,
        CHARACTER = 5,
        CHARACTEREOL = 6,
        STRING = 7,
        STRINGEOL = 8,
        LABEL = 9,
        COMMENTLINE = 10,
        ILLEGAL = 11,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum BAAN
    {    
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTDOC = 2,
        NUMBER = 3,
        WORD = 4,
        STRING = 5,
        PREPROCESSOR = 6,
        OPERATOR = 7,
        IDENTIFIER = 8,
        STRINGEOL = 9,
        WORD2 = 10,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum LISP
    {    
        DEFAULT = 0,
        COMMENT = 1,
        NUMBER = 2,
        KEYWORD = 3,
        KEYWORD_KW = 4,
        SYMBOL = 5,
        STRING = 6,
        STRINGEOL = 8,
        IDENTIFIER = 9,
        OPERATOR = 10,
        SPECIAL = 11,
        MULTI_COMMENT = 12,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum EIFFEL
    {    
        DEFAULT = 0,
        COMMENTLINE = 1,
        NUMBER = 2,
        WORD = 3,
        STRING = 4,
        CHARACTER = 5,
        OPERATOR = 6,
        IDENTIFIER = 7,
        STRINGEOL = 8,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum EIFFELKW
    {    
        DEFAULT = 0,
        COMMENTLINE = 1,
        NUMBER = 2,
        WORD = 3,
        STRING = 4,
        CHARACTER = 5,
        OPERATOR = 6,
        IDENTIFIER = 7,
        STRINGEOL = 8,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum NNCRONTAB
    {    
        DEFAULT = 0,
        COMMENT = 1,
        TASK = 2,
        SECTION = 3,
        KEYWORD = 4,
        MODIFIER = 5,
        ASTERISK = 6,
        NUMBER = 7,
        STRING = 8,
        ENVIRONMENT = 9,
        IDENTIFIER = 10,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum FORTH
    {    
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTML = 2,
        IDENTIFIER = 3,
        CONTROL = 4,
        KEYWORD = 5,
        DEFWORD = 6,
        PREWORD1 = 7,
        PREWORD2 = 8,
        NUMBER = 9,
        STRING = 10,
        LOCALE = 11,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum MATLAB
    {    
        DEFAULT = 0,
        COMMENT = 1,
        COMMAND = 2,
        NUMBER = 3,
        KEYWORD = 4,
        STRING = 5,
        OPERATOR = 6,
        IDENTIFIER = 7,
        DOUBLEQUOTESTRING = 8,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum SCRIPTOL
    {    
        DEFAULT = 0,
        WHITE = 1,
        COMMENTLINE = 2,
        PERSISTENT = 3,
        CSTYLE = 4,
        COMMENTBLOCK = 5,
        NUMBER = 6,
        STRING = 7,
        CHARACTER = 8,
        STRINGEOL = 9,
        KEYWORD = 10,
        OPERATOR = 11,
        IDENTIFIER = 12,
        TRIPLE = 13,
        CLASSNAME = 14,
        PREPROCESSOR = 15,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum ASM
    {    
        DEFAULT = 0,
        COMMENT = 1,
        NUMBER = 2,
        STRING = 3,
        OPERATOR = 4,
        IDENTIFIER = 5,
        CPUINSTRUCTION = 6,
        MATHINSTRUCTION = 7,
        REGISTER = 8,
        DIRECTIVE = 9,
        DIRECTIVEOPERAND = 10,
        COMMENTBLOCK = 11,
        CHARACTER = 12,
        STRINGEOL = 13,
        EXTINSTRUCTION = 14,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum FORTRAN
    {    
        DEFAULT = 0,
        COMMENT = 1,
        NUMBER = 2,
        STRING1 = 3,
        STRING2 = 4,
        STRINGEOL = 5,
        OPERATOR = 6,
        IDENTIFIER = 7,
        WORD = 8,
        WORD2 = 9,
        WORD3 = 10,
        PREPROCESSOR = 11,
        OPERATOR2 = 12,
        LABEL = 13,
        CONTINUATION = 14,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum F77
    {    
        DEFAULT = 0,
        COMMENT = 1,
        NUMBER = 2,
        STRING1 = 3,
        STRING2 = 4,
        STRINGEOL = 5,
        OPERATOR = 6,
        IDENTIFIER = 7,
        WORD = 8,
        WORD2 = 9,
        WORD3 = 10,
        PREPROCESSOR = 11,
        OPERATOR2 = 12,
        LABEL = 13,
        CONTINUATION = 14,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum CSS
    {    
        DEFAULT = 0,
        TAG = 1,
        CLASS = 2,
        PSEUDOCLASS = 3,
        UNKNOWN_PSEUDOCLASS = 4,
        OPERATOR = 5,
        IDENTIFIER = 6,
        UNKNOWN_IDENTIFIER = 7,
        VALUE = 8,
        COMMENT = 9,
        ID = 10,
        IMPORTANT = 11,
        DIRECTIVE = 12,
        DOUBLESTRING = 13,
        SINGLESTRING = 14,
        IDENTIFIER2 = 15,
        ATTRIBUTE = 16,
        IDENTIFIER3 = 17,
        PSEUDOELEMENT = 18,
        EXTENDED_IDENTIFIER = 19,
        EXTENDED_PSEUDOCLASS = 20,
        EXTENDED_PSEUDOELEMENT = 21,
        MEDIA = 22,
        VARIABLE = 23,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum POV
    {    
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTLINE = 2,
        NUMBER = 3,
        OPERATOR = 4,
        IDENTIFIER = 5,
        STRING = 6,
        STRINGEOL = 7,
        DIRECTIVE = 8,
        BADDIRECTIVE = 9,
        WORD2 = 10,
        WORD3 = 11,
        WORD4 = 12,
        WORD5 = 13,
        WORD6 = 14,
        WORD7 = 15,
        WORD8 = 16,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum LOUT
    {    
        DEFAULT = 0,
        COMMENT = 1,
        NUMBER = 2,
        WORD = 3,
        WORD2 = 4,
        WORD3 = 5,
        WORD4 = 6,
        STRING = 7,
        OPERATOR = 8,
        IDENTIFIER = 9,
        STRINGEOL = 10,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum ESCRIPT
    {    
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTLINE = 2,
        COMMENTDOC = 3,
        NUMBER = 4,
        WORD = 5,
        STRING = 6,
        OPERATOR = 7,
        IDENTIFIER = 8,
        BRACE = 9,
        WORD2 = 10,
        WORD3 = 11,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum PS
    {    
        DEFAULT = 0,
        COMMENT = 1,
        DSCCOMMENT = 2,
        DSCVALUE = 3,
        NUMBER = 4,
        NAME = 5,
        KEYWORD = 6,
        LITERAL = 7,
        IMMEVAL = 8,
        PARENARRAY = 9,
        PARENDICT = 10,
        PARENPROC = 11,
        TEXT = 12,
        HEXSTRING = 13,
        BASE85STRING = 14,
        BADSTRINGCHAR = 15,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum NSIS
    {    
        DEFAULT = 0,
        COMMENT = 1,
        STRINGDQ = 2,
        STRINGLQ = 3,
        STRINGRQ = 4,
        FUNCTION = 5,
        VARIABLE = 6,
        LABEL = 7,
        USERDEFINED = 8,
        SECTIONDEF = 9,
        SUBSECTIONDEF = 10,
        IFDEFINEDEF = 11,
        MACRODEF = 12,
        STRINGVAR = 13,
        NUMBER = 14,
        SECTIONGROUP = 15,
        PAGEEX = 16,
        FUNCTIONDEF = 17,
        COMMENTBOX = 18,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum MMIXAL
    {    
        LEADWS = 0,
        COMMENT = 1,
        LABEL = 2,
        OPCODE = 3,
        OPCODEPRE = 4,
        OPCODEVALID = 5,
        OPCODEUNKNOWN = 6,
        OPCODEPOST = 7,
        OPERANDS = 8,
        NUMBER = 9,
        REF = 10,
        CHAR = 11,
        STRING = 12,
        REGISTER = 13,
        HEX = 14,
        OPERATOR = 15,
        SYMBOL = 16,
        INCLUDE = 17,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum CLARION
    {    
        DEFAULT = 0,
        LABEL = 1,
        COMMENT = 2,
        STRING = 3,
        USER_IDENTIFIER = 4,
        INTEGER_CONSTANT = 5,
        REAL_CONSTANT = 6,
        PICTURE_STRING = 7,
        KEYWORD = 8,
        COMPILER_DIRECTIVE = 9,
        RUNTIME_EXPRESSIONS = 10,
        BUILTIN_PROCEDURES_FUNCTION = 11,
        STRUCTURE_DATA_TYPE = 12,
        ATTRIBUTE = 13,
        STANDARD_EQUATE = 14,
        ERROR = 15,
        DEPRECATED = 16,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum LOT
    {    
        DEFAULT = 0,
        HEADER = 1,
        BREAK = 2,
        SET = 3,
        PASS = 4,
        FAIL = 5,
        ABORT = 6,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum YAML
    {    
        DEFAULT = 0,
        COMMENT = 1,
        IDENTIFIER = 2,
        KEYWORD = 3,
        NUMBER = 4,
        REFERENCE = 5,
        DOCUMENT = 6,
        TEXT = 7,
        ERROR = 8,
        OPERATOR = 9,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum TEX
    {    
        DEFAULT = 0,
        SPECIAL = 1,
        GROUP = 2,
        SYMBOL = 3,
        COMMAND = 4,
        TEXT = 5,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum METAPOST
    {    
        DEFAULT = 0,
        SPECIAL = 1,
        GROUP = 2,
        SYMBOL = 3,
        COMMAND = 4,
        TEXT = 5,
        EXTRA = 6,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum ERLANG
    {    
        DEFAULT = 0,
        COMMENT = 1,
        VARIABLE = 2,
        NUMBER = 3,
        KEYWORD = 4,
        STRING = 5,
        OPERATOR = 6,
        ATOM = 7,
        FUNCTIONNAME = 8,
        CHARACTER = 9,
        MACRO = 10,
        RECORD = 11,
        SEPARATOR = 12,
        NODENAME = 13,
        UNKNOWN = 31,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum OCTAVE
    {
        DEFAULT = 0,
        COMMENT = 1,
        COMMAND = 2,
        NUMBER = 3,
        KEYWORD = 4,
        STRING = 5,
        OPERATOR = 6,
        IDENTIFIER = 7,
        DOUBLEQUOTESTRING = 8,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum MSSQL
    {    
        DEFAULT = 0,
        COMMENT = 1,
        LINE_COMMENT = 2,
        NUMBER = 3,
        STRING = 4,
        OPERATOR = 5,
        IDENTIFIER = 6,
        VARIABLE = 7,
        COLUMN_NAME = 8,
        STATEMENT = 9,
        DATATYPE = 10,
        SYSTABLE = 11,
        GLOBAL_VARIABLE = 12,
        FUNCTION = 13,
        STORED_PROCEDURE = 14,
        DEFAULT_PREF_DATATYPE = 15,
        COLUMN_NAME_2 = 16,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum VERILOG
    {    
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTLINE = 2,
        COMMENTLINEBANG = 3,
        NUMBER = 4,
        WORD = 5,
        STRING = 6,
        WORD2 = 7,
        WORD3 = 8,
        PREPROCESSOR = 9,
        OPERATOR = 10,
        IDENTIFIER = 11,
        STRINGEOL = 12,
        USER = 19,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum KIX
    {    
        DEFAULT = 0,
        COMMENT = 1,
        STRING1 = 2,
        STRING2 = 3,
        NUMBER = 4,
        VAR = 5,
        MACRO = 6,
        KEYWORD = 7,
        FUNCTIONS = 8,
        OPERATOR = 9,
        IDENTIFIER = 31,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum GUI4CLI
    {    
        DEFAULT = 0,
        COMMENTLINE = 1,
        COMMENTBLOCK = 2,
        GLOBAL = 3,
        EVENT = 4,
        ATTRIBUTE = 5,
        CONTROL = 6,
        COMMAND = 7,
        STRING = 8,
        OPERATOR = 9,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum SPECMAN
    {    
        DEFAULT = 0,
        CODE = 1,
        COMMENTLINE = 2,
        COMMENTLINEBANG = 3,
        NUMBER = 4,
        WORD = 5,
        STRING = 6,
        WORD2 = 7,
        WORD3 = 8,
        PREPROCESSOR = 9,
        OPERATOR = 10,
        IDENTIFIER = 11,
        STRINGEOL = 12,
        REGEXTAG = 13,
        SIGNAL = 14,
        USER = 19,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum AU3
    {    
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTBLOCK = 2,
        NUMBER = 3,
        FUNCTION = 4,
        KEYWORD = 5,
        MACRO = 6,
        STRING = 7,
        OPERATOR = 8,
        VARIABLE = 9,
        SENT = 10,
        PREPROCESSOR = 11,
        SPECIAL = 12,
        EXPAND = 13,
        COMOBJ = 14,
        UDF = 15,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum APDL
    {    
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTBLOCK = 2,
        NUMBER = 3,
        STRING = 4,
        OPERATOR = 5,
        WORD = 6,
        PROCESSOR = 7,
        COMMAND = 8,
        SLASHCOMMAND = 9,
        STARCOMMAND = 10,
        ARGUMENT = 11,
        FUNCTION = 12,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum BASH
    {    
        DEFAULT = 0,
        ERROR = 1,
        COMMENTLINE = 2,
        NUMBER = 3,
        WORD = 4,
        STRING = 5,
        CHARACTER = 6,
        OPERATOR = 7,
        IDENTIFIER = 8,
        SCALAR = 9,
        PARAM = 10,
        BACKTICKS = 11,
        HERE_DELIM = 12,
        HERE_Q = 13,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum ASN1
    {    
        DEFAULT = 0,
        COMMENT = 1,
        IDENTIFIER = 2,
        STRING = 3,
        OID = 4,
        SCALAR = 5,
        KEYWORD = 6,
        ATTRIBUTE = 7,
        DESCRIPTOR = 8,
        TYPE = 9,
        OPERATOR = 10,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum VHDL
    {    
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTLINEBANG = 2,
        NUMBER = 3,
        STRING = 4,
        OPERATOR = 5,
        IDENTIFIER = 6,
        STRINGEOL = 7,
        KEYWORD = 8,
        STDOPERATOR = 9,
        ATTRIBUTE = 10,
        STDFUNCTION = 11,
        STDPACKAGE = 12,
        STDTYPE = 13,
        USERWORD = 14,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum CAML
    {    
        DEFAULT = 0,
        IDENTIFIER = 1,
        TAGNAME = 2,
        KEYWORD = 3,
        KEYWORD2 = 4,
        KEYWORD3 = 5,
        LINENUM = 6,
        OPERATOR = 7,
        NUMBER = 8,
        CHAR = 9,
        STRING = 11,
        COMMENT = 12,
        COMMENT1 = 13,
        COMMENT2 = 14,
        COMMENT3 = 15,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum HASKELL
    {    
        DEFAULT = 0,
        IDENTIFIER = 1,
        KEYWORD = 2,
        NUMBER = 3,
        STRING = 4,
        CHARACTER = 5,
        CLASS = 6,
        MODULE = 7,
        CAPITAL = 8,
        DATA = 9,
        IMPORT = 10,
        OPERATOR = 11,
        INSTANCE = 12,
        COMMENTLINE = 13,
        COMMENTBLOCK = 14,
        COMMENTBLOCK2 = 15,
        COMMENTBLOCK3 = 16,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum TADS3
    {    
        DEFAULT = 0,
        X_DEFAULT = 1,
        PREPROCESSOR = 2,
        BLOCK_COMMENT = 3,
        LINE_COMMENT = 4,
        OPERATOR = 5,
        KEYWORD = 6,
        NUMBER = 7,
        IDENTIFIER = 8,
        S_STRING = 9,
        D_STRING = 10,
        X_STRING = 11,
        LIB_DIRECTIVE = 12,
        MSG_PARAM = 13,
        HTML_TAG = 14,
        HTML_DEFAULT = 15,
        HTML_STRING = 16,
        USER1 = 17,
        USER2 = 18,
        USER3 = 19,
        BRACE = 20,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum REBOL
    {    
        DEFAULT = 0,
        COMMENTLINE = 1,
        COMMENTBLOCK = 2,
        PREFACE = 3,
        OPERATOR = 4,
        CHARACTER = 5,
        QUOTEDSTRING = 6,
        BRACEDSTRING = 7,
        NUMBER = 8,
        PAIR = 9,
        TUPLE = 10,
        BINARY = 11,
        MONEY = 12,
        ISSUE = 13,
        TAG = 14,
        FILE = 15,
        EMAIL = 16,
        URL = 17,
        DATE = 18,
        TIME = 19,
        IDENTIFIER = 20,
        WORD = 21,
        WORD2 = 22,
        WORD3 = 23,
        WORD4 = 24,
        WORD5 = 25,
        WORD6 = 26,
        WORD7 = 27,
        WORD8 = 28,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum SQL
    {    
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTLINE = 2,
        COMMENTDOC = 3,
        NUMBER = 4,
        WORD = 5,
        STRING = 6,
        CHARACTER = 7,
        SQLPLUS = 8,
        SQLPLUS_PROMPT = 9,
        OPERATOR = 10,
        IDENTIFIER = 11,
        SQLPLUS_COMMENT = 13,
        COMMENTLINEDOC = 15,
        WORD2 = 16,
        COMMENTDOCKEYWORD = 17,
        COMMENTDOCKEYWORDERROR = 18,
        USER1 = 19,
        USER2 = 20,
        USER3 = 21,
        USER4 = 22,
        QUOTEDIDENTIFIER = 23,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum SMALLTALK
    {    
        DEFAULT = 0,
        STRING = 1,
        NUMBER = 2,
        COMMENT = 3,
        SYMBOL = 4,
        BINARY = 5,
        BOOL = 6,
        SELF = 7,
        SUPER = 8,
        NIL = 9,
        GLOBAL = 10,
        RETURN = 11,
        SPECIAL = 12,
        KWSEND = 13,
        ASSIGN = 14,
        CHARACTER = 15,
        SPEC_SEL = 16,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum FLAGSHIP
    {    
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTLINE = 2,
        COMMENTDOC = 3,
        COMMENTLINEDOC = 4,
        COMMENTDOCKEYWORD = 5,
        COMMENTDOCKEYWORDERROR = 6,
        KEYWORD = 7,
        KEYWORD2 = 8,
        KEYWORD3 = 9,
        KEYWORD4 = 10,
        NUMBER = 11,
        STRING = 12,
        PREPROCESSOR = 13,
        OPERATOR = 14,
        IDENTIFIER = 15,
        DATE = 16,
        STRINGEOL = 17,
        CONSTANT = 18,
        ASM = 19,
        LABEL = 20,
        ERROR = 21,
        HEXNUMBER = 22,
        BINNUMBER = 23,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }
    
    public enum CSOUND
    {    
        DEFAULT = 0,
        COMMENT = 1,
        NUMBER = 2,
        OPERATOR = 3,
        INSTR = 4,
        IDENTIFIER = 5,
        OPCODE = 6,
        HEADERSTMT = 7,
        USERKEYWORD = 8,
        COMMENTBLOCK = 9,
        PARAM = 10,
        ARATE_VAR = 11,
        KRATE_VAR = 12,
        IRATE_VAR = 13,
        GLOBAL_VAR = 14,
        STRINGEOL = 15,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum INNOSETUP 
    {
        DEFAULT = 0,
        COMMENT = 1,
        KEYWORD = 2,
        PARAMETER = 3,
        SECTION = 4,
        PREPROC = 5,
        PREPROC_INLINE = 6,
        COMMENT_PASCAL = 7,
        KEYWORD_PASCAL = 8,
        KEYWORD_USER = 9,
        STRING_DOUBLE = 10,
        STRING_SINGLE = 11,
        IDENTIFIER = 12,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum OPAL
    {
        SPACE = 0,
        COMMENT_BLOCK = 1,
        COMMENT_LINE = 2,
        INTEGER = 3,
        KEYWORD = 4,
        SORT = 5,
        STRING = 6,
        PAR = 7,
        BOOL_CONST = 8,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum SPICE
    {
        DEFAULT = 0,
        IDENTIFIER = 1,
        KEYWORD = 2,
        KEYWORD2 = 3,
        KEYWORD3 = 4,
        NUMBER = 5,
        DELIMITER = 6,
        VALUE = 7,
        COMMENTLINE = 8,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum CMAKE
    {
        DEFAULT = 0,
        COMMENT = 1,
        STRINGDQ = 2,
        STRINGLQ = 3,
        STRINGRQ = 4,
        COMMANDS = 5,
        PARAMETERS = 6,
        VARIABLE = 7,
        USERDEFINED = 8,
        WHILEDEF = 9,
        FOREACHDEF = 10,
        IFDEFINEDEF = 11,
        MACRODEF = 12,
        STRINGVAR = 13,
        NUMBER = 14,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum GAP
    {
        DEFAULT = 0,
        IDENTIFIER = 1,
        KEYWORD = 2,
        KEYWORD2 = 3,
        KEYWORD3 = 4,
        KEYWORD4 = 5,
        STRING = 6,
        CHAR = 7,
        OPERATOR = 8,
        COMMENT = 9,
        NUMBER = 10,
        STRINGEOL = 11,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum PLM
    {
        DEFAULT = 0,
        COMMENT = 1,
        STRING = 2,
        NUMBER = 3,
        IDENTIFIER = 4,
        OPERATOR = 5,
        CONTROL = 6,
        KEYWORD = 7,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum PROGRESS
    {
        DEFAULT = 0,
        NUMBER = 1,
        WORD = 2,
        STRING = 3,
        CHARACTER = 4,
        PREPROCESSOR = 5,
        OPERATOR = 6,
        IDENTIFIER = 7,
        BLOCK = 8,
        END = 9,
        COMMENT1 = 10,
        COMMENT2 = 11,
        COMMENT3 = 12,
        COMMENT4 = 13,
        COMMENT5 = 14,
        COMMENT6 = 15,
        DEFAULT_ = 16,
        NUMBER_ = 17,
        WORD_ = 18,
        STRING_ = 19,
        CHARACTER_ = 20,
        PREPROCESSOR_ = 21,
        OPERATOR_ = 22,
        IDENTIFIER_ = 23,
        BLOCK_ = 24,
        END_ = 25,
        COMMENT1_ = 26,
        COMMENT2_ = 27,
        COMMENT3_ = 28,
        COMMENT4_ = 29,
        COMMENT5_ = 30,
        COMMENT6_ = 31,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum ABAQUS
    {
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTBLOCK = 2,
        NUMBER = 3,
        STRING = 4,
        OPERATOR = 5,
        WORD = 6,
        PROCESSOR = 7,
        COMMAND = 8,
        SLASHCOMMAND = 9,
        STARCOMMAND = 10,
        ARGUMENT = 11,
        FUNCTION = 12,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum ASYMPTOTE
    {
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTLINE = 2,
        NUMBER = 3,
        WORD = 4,
        STRING = 5,
        CHARACTER = 6,
        OPERATOR = 7,
        IDENTIFIER = 8,
        STRINGEOL = 9,
        COMMENTLINEDOC = 10,
        WORD2 = 11,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum R
    {
        DEFAULT = 0,
        COMMENT = 1,
        KWORD = 2,
        BASEKWORD = 3,
        OTHERKWORD = 4,
        NUMBER = 5,
        STRING = 6,
        STRING2 = 7,
        OPERATOR = 8,
        IDENTIFIER = 9,
        INFIX = 10,
        INFIXEOL = 11,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum MAGIK
    {
        DEFAULT = 0,
        COMMENT = 1,
        HYPER_COMMENT = 16,
        STRING = 2,
        CHARACTER = 3,
        NUMBER = 4,
        IDENTIFIER = 5,
        OPERATOR = 6,
        FLOW = 7,
        CONTAINER = 8,
        BRACKET_BLOCK = 9,
        BRACE_BLOCK = 10,
        SQBRACKET_BLOCK = 11,
        UNKNOWN_KEYWORD = 12,
        KEYWORD = 13,
        PRAGMA = 14,
        SYMBOL = 15,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum POWERSHELL
    {
        DEFAULT = 0,
        COMMENT = 1,
        STRING = 2,
        CHARACTER = 3,
        NUMBER = 4,
        VARIABLE = 5,
        OPERATOR = 6,
        IDENTIFIER = 7,
        KEYWORD = 8,
        CMDLET = 9,
        ALIAS = 10,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum MYSQL
    {
        DEFAULT = 0,
        COMMENT = 1,
        COMMENTLINE = 2,
        VARIABLE = 3,
        SYSTEMVARIABLE = 4,
        KNOWNSYSTEMVARIABLE = 5,
        NUMBER = 6,
        MAJORKEYWORD = 7,
        KEYWORD = 8,
        DATABASEOBJECT = 9,
        PROCEDUREKEYWORD = 10,
        STRING = 11,
        SQSTRING = 12,
        DQSTRING = 13,
        OPERATOR = 14,
        FUNCTION = 15,
        IDENTIFIER = 16,
        QUOTEDIDENTIFIER = 17,
        USER1 = 18,
        USER2 = 19,
        USER3 = 20,
        HIDDENCOMMAND = 21,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum PO
    {
        DEFAULT = 0,
        COMMENT = 1,
        MSGID = 2,
        MSGID_TEXT = 3,
        MSGSTR = 4,
        MSGSTR_TEXT = 5,
        MSGCTXT = 6,
        MSGCTXT_TEXT = 7,
        FUZZY = 8,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum PASCAL
    {
        DEFAULT = 0,
        IDENTIFIER = 1,
        COMMENT = 2,
        COMMENT2 = 3,
        COMMENTLINE = 4,
        PREPROCESSOR = 5,
        PREPROCESSOR2 = 6,
        NUMBER = 7,
        HEXNUMBER = 8,
        WORD = 9,
        STRING = 10,
        STRINGEOL = 11,
        CHARACTER = 12,
        OPERATOR = 13,
        ASM = 14,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum SORCUS
    {
        DEFAULT = 0,
        COMMAND = 1,
        PARAMETER = 2,
        COMMENTLINE = 3,
        STRING = 4,
        STRINGEOL = 5,
        IDENTIFIER = 6,
        OPERATOR = 7,
        NUMBER = 8,
        CONSTANT = 9,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

    public enum POWERPRO
    {
        DEFAULT = 0,
        COMMENTBLOCK = 1,
        COMMENTLINE = 2,
        NUMBER = 3,
        WORD = 4,
        WORD2 = 5,
        WORD3 = 6,
        WORD4 = 7,
        DOUBLEQUOTEDSTRING = 8,
        SINGLEQUOTEDSTRING = 9,
        LINECONTINUE = 10,
        OPERATOR = 11,
        IDENTIFIER = 12,
        STRINGEOL = 13,
        VERBATIM = 14,
        ALTQUOTE = 15,
        FUNCTION = 16,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39,
    }

    public enum SML
    {
        DEFAULT = 0,
        IDENTIFIER = 1,
        TAGNAME = 2,
        KEYWORD = 3,
        KEYWORD2 = 4,
        KEYWORD3 = 5,
        LINENUM = 6,
        OPERATOR = 7,
        NUMBER = 8,
        CHAR = 9,
        STRING = 11,
        COMMENT = 12,
        COMMENT1 = 13,
        COMMENT2 = 14,
        COMMENT3 = 15,
        GDEFAULT = 32,
        LINENUMBER = 33,
        BRACELIGHT = 34,
        BRACEBAD = 35,
        CONTROLCHAR = 36,
        INDENTGUIDE = 37,
        LASTPREDEFINED = 39
    }

}
